/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab02;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        Simple_Test classUnderTest = new Simple_Test();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
