/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab02;

public class Simple_Test {
    public String getGreeting() {
        return "Hello";
    }

    public static void main(String[] args) {
        System.out.println(new Simple_Test().getGreeting());
    }
}
